In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/housepricedata (1).csv')

In [ ]:
df.head()

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0     8450            7            5          856         2         1   
1     9600            6            8         1262         2         0   
2    11250            7            5          920         2         1   
3     9550            7            5          756         1         0   
4    14260            8            5         1145         2         1   

   BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
0             3             8           0         548                 1  
1             3             6           1         460                 1  
2             3             6           1         608                 1  
3             3             7           1         642                 0  
4             4             9           1         836                 1

In [ ]:
df.shape

(1460, 11)

In [ ]:
df.columns

Index(['LotArea', 'OverallQual', 'OverallCond', 'TotalBsmtSF', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageArea',
       'AboveMedianPrice'],
      dtype='object')

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   LotArea           1460 non-null   int64
 1   OverallQual       1460 non-null   int64
 2   OverallCond       1460 non-null   int64
 3   TotalBsmtSF       1460 non-null   int64
 4   FullBath          1460 non-null   int64
 5   HalfBath          1460 non-null   int64
 6   BedroomAbvGr      1460 non-null   int64
 7   TotRmsAbvGrd      1460 non-null   int64
 8   Fireplaces        1460 non-null   int64
 9   GarageArea        1460 non-null   int64
 10  AboveMedianPrice  1460 non-null   int64
dtypes: int64(11)
memory usage: 125.6 KB


In [ ]:
df.describe()

LotArea  OverallQual  OverallCond  TotalBsmtSF     FullBath  \
count    1460.000000  1460.000000  1460.000000  1460.000000  1460.000000   
mean    10516.828082     6.099315     5.575342  1057.429452     1.565068   
std      9981.264932     1.382997     1.112799   438.705324     0.550916   
min      1300.000000     1.000000     1.000000     0.000000     0.000000   
25%      7553.500000     5.000000     5.000000   795.750000     1.000000   
50%      9478.500000     6.000000     5.000000   991.500000     2.000000   
75%     11601.500000     7.000000     6.000000  1298.250000     2.000000   
max    215245.000000    10.000000     9.000000  6110.000000     3.000000   

          HalfBath  BedroomAbvGr  TotRmsAbvGrd   Fireplaces   GarageArea  \
count  1460.000000   1460.000000   1460.000000  1460.000000  1460.000000   
mean      0.382877      2.866438      6.517808     0.613014   472.980137   
std       0.502885      0.815778      1.625393     0.644666   213.804841   
min       0.000000      0.000000      2.000000     0.000000     0.000000   
25%       0.000000      2.000000      5.000000     0.000000   334.500000   
50%       0.000000      3.000000      6.000000     1.000000   480.000000   
75%       1.000000      3.000000      7.000000     1.000000   576.000000   
max       2.000000      8.000000     14.000000     3.000000  1418.000000   

       AboveMedianPrice  
count       1460.000000  
mean           0.498630  
std            0.500169  
min            0.000000  
25%            0.000000  
50%            0.000000  
75%            1.000000  
max            1.000000

In [ ]:
df.loc[2.4:10]

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
3      9550            7            5          756         1         0   
4     14260            8            5         1145         2         1   
5     14115            5            5          796         1         1   
6     10084            8            5         1686         2         0   
7     10382            7            6         1107         2         1   
8      6120            7            5          952         2         0   
9      7420            5            6          991         1         0   
10    11200            5            5         1040         1         0   

    BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
3              3             7           1         642                 0  
4              4             9           1         836                 1  
5              1             5           0         480                 0  
6              3             7           1         636                 1  
7              3             7           2         484                 1  
8              2             8           2         468                 0  
9              2             5           2         205                 0  
10             3             5           0         384                 0

In [ ]:
df.iloc[2:10]

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
2    11250            7            5          920         2         1   
3     9550            7            5          756         1         0   
4    14260            8            5         1145         2         1   
5    14115            5            5          796         1         1   
6    10084            8            5         1686         2         0   
7    10382            7            6         1107         2         1   
8     6120            7            5          952         2         0   
9     7420            5            6          991         1         0   

   BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
2             3             6           1         608                 1  
3             3             7           1         642                 0  
4             4             9           1         836                 1  
5             1             5           0         480                 0  
6             3             7           1         636                 1  
7             3             7           2         484                 1  
8             2             8           2         468                 0  
9             2             5           2         205                 0

In [ ]:
df.isnull().sum()

LotArea             0
OverallQual         0
OverallCond         0
TotalBsmtSF         0
FullBath            0
HalfBath            0
BedroomAbvGr        0
TotRmsAbvGrd        0
Fireplaces          0
GarageArea          0
AboveMedianPrice    0
dtype: int64

In [ ]:
df.dropna()

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0        8450            7            5          856         2         1   
1        9600            6            8         1262         2         0   
2       11250            7            5          920         2         1   
3        9550            7            5          756         1         0   
4       14260            8            5         1145         2         1   
...       ...          ...          ...          ...       ...       ...   
1455     7917            6            5          953         2         1   
1456    13175            6            6         1542         2         0   
1457     9042            7            9         1152         2         0   
1458     9717            5            6         1078         1         0   
1459     9937            5            6         1256         1         1   

      BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
0                3             8           0         548                 1  
1                3             6           1         460                 1  
2                3             6           1         608                 1  
3                3             7           1         642                 0  
4                4             9           1         836                 1  
...            ...           ...         ...         ...               ...  
1455             3             7           1         460                 1  
1456             3             7           2         500                 1  
1457             4             9           2         252                 1  
1458             2             5           0         240                 0  
1459             3             6           0         276                 0  

[1460 rows x 11 columns]

In [ ]:
np.isnan(df.values).any()

False

In [ ]:
x=df.iloc[:,0:9].values

In [ ]:
x

array([[ 8450,     7,     5, ...,     3,     8,     0],
       [ 9600,     6,     8, ...,     3,     6,     1],
       [11250,     7,     5, ...,     3,     6,     1],
       ...,
       [ 9042,     7,     9, ...,     4,     9,     2],
       [ 9717,     5,     6, ...,     2,     5,     0],
       [ 9937,     5,     6, ...,     3,     6,     0]])

In [ ]:
y=df.iloc[:,10].values
y

array([1, 1, 1, ..., 1, 0, 0])

In [ ]:
type(y)

numpy.ndarray

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test=train_test_split(x,y,test_size=0.30,random_state=200)

In [ ]:
x_train


array([[14157,     9,     5, ...,     3,     8,     1],
       [11049,     8,     5, ...,     3,     7,     0],
       [ 3180,     7,     5, ...,     2,     4,     0],
       ...,
       [10140,     6,     6, ...,     3,     5,     1],
       [ 6300,     6,     6, ...,     3,     9,     1],
       [ 7227,     6,     6, ...,     2,     4,     0]])

In [ ]:
x_test

array([[ 7931,     5,     5, ...,     3,     6,     0],
       [ 5720,     5,     6, ...,     3,     5,     0],
       [11767,     4,     7, ...,     2,     6,     0],
       ...,
       [ 5381,     6,     5, ...,     1,     5,     1],
       [ 5436,     4,     8, ...,     3,     7,     0],
       [ 9120,     7,     6, ...,     4,     8,     0]])

In [ ]:
from sklearn import preprocessing 
min_max_scaler = preprocessing.MinMaxScaler()
x_scale=min_max_scaler.fit_transform(x_train)

In [ ]:
x_scale

array([[0.06009488, 0.88888889, 0.5       , ..., 0.375     , 0.5       ,
        0.33333333],
       [0.04556779, 0.77777778, 0.5       , ..., 0.375     , 0.41666667,
        0.        ],
       [0.00878731, 0.66666667, 0.5       , ..., 0.25      , 0.16666667,
        0.        ],
       ...,
       [0.04131903, 0.55555556, 0.625     , ..., 0.375     , 0.25      ,
        0.33333333],
       [0.02337049, 0.55555556, 0.625     , ..., 0.375     , 0.58333333,
        0.33333333],
       [0.02770338, 0.55555556, 0.625     , ..., 0.25      , 0.16666667,
        0.        ]])

In [ ]:
print(x_test.shape)

(438, 9)


In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
y_pred

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,

In [ ]:
from sklearn.metrics import accuracy_score
print("accuracy:", accuracy_score(y_test,y_pred))

accuracy: 0.8242009132420092
